services:
  cache-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db.sqlite:/app/db.sqlite

  redis:
    image: "redis:6.2.16-alpine"
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: