GET http://localhost:3001/redis?bruno

###

POST http://localhost:3001/redis
Content-type: application/json

{
  "key": "bruno",
  "value": {
    "nome": "Bruno",
    "sobrenome": "Santana",
    "idade": 27
  }
}